CREATE TABLE IF NOT EXISTS cars (
    id INT NOT NULL AUTO_INCREMENT,
    make VARCHAR(100),
    model VARCHAR(100),
    _condition VARCHAR(50),
    source VARCHAR(100),
    is_scraped TINYINT,
    is_prescraped TINYINT,
    url VARCHAR(255),
    trim_information LONGTEXT,
    price INT,
    year VARCHAR(50),
    mileage VARCHAR(50),
    reviews INT,
    reviews_link VARCHAR(255),
    photos LONGTEXT,
    stock INT,
    vin VARCHAR(100),
    dealer MEDIUMTEXT,
    key_features VARCHAR(255),
    key_specs VARCHAR(255),
    color VARCHAR(100),
    base_specs LONGTEXT,
    base_features LONGTEXT,
    nhtsa_rating VARCHAR(255),
    jd_rating VARCHAR(255),
    PRIMARY KEY (id),
    UNIQUE KEY url_key (url)
);

